---
- name: Add nfs-common
  ansible.builtin.apt:
    name: nfs-common
    state: present
  when: nfsstorage

- name: Create a NFS storage directory if it does not exist
  ansible.builtin.file:
    path: '{{ nfslocalpath }}'
    state: directory
    mode: '0755'
  when: nfsstorage

- name: Mount NFS
  ansible.posix.mount:
    path: '{{ nfslocalpath }}'
    src: '{{ nfsremotepath }}'
    fstype: nfs
    state: mounted
  when: nfsstorage