---
# handlers file for kubcluster
- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Restart netplan smitkub1
  ansible.builtin.command: /bin/bash /tmp/netplan_apply.sh
  poll: 0
  async: 45
  changed_when: true
  when: inventory_hostname == "smitkub1.smithsonite.home"

- name: Restart netplan smitkub2
  ansible.builtin.command: /bin/bash /tmp/netplan_apply.sh
  poll: 0
  async: 45
  changed_when: true
  when: inventory_hostname == "smitkub2.smithsonite.home"

- name: Restart netplan smitkub3
  ansible.builtin.command: /bin/bash /tmp/netplan_apply.sh
  poll: 0
  async: 45
  changed_when: true
  when: inventory_hostname == "smitkub3.smithsonite.home"

- name: Restart netplan autobot
  ansible.builtin.command: /bin/bash /tmp/netplan_apply.sh
  poll: 0
  async: 45
  changed_when: true
  when: inventory_hostname == "localhost"
