---
# handlers file for kubcluster
- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true
