---
# handlers file for kubcluster
- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Restart netplan
  ansible.builtin.command: /bin/bash /tmp/netplan_apply.sh
  poll: 0
  async: 45
  changed_when: true
